### ISSUE TITLE
Upload and Staging 5.9.0 to OpsManager fails (Datadog Cluster Monitoring for VMware Tanzu)

### ISSUE THREAD

**Issue by sritimmaraju** [DataDog/datadog-cluster-monitoring-pivotal-tile#109]
**Error when uploading/staging the tile to OpsMananger*
is invalid: Property blueprints : [21] cannot be optional and have a default value 

**To Reproduce**
1. Download 5.9.0 from [PivotalNetwork](https://network.pivotal.io/products/datadog/#/releases/1412967])
2. Login to OpsManager
3. Click on Import a Product and upload the 5.9.0 version of Datadog Cluster Monitoring for VMware Tanzu
<img width="1376" alt="Screenshot 2023-11-29 at 11 45 38 AM" src="https://github.com/DataDog/datadog-cluster-monitoring-pivotal-tile/assets/43353148/669a2d66-0d48-4b48-bbdc-de5df9e4c38f">

**Comment by NouemanKHAL** [comment]
Hi @sritimmaraju,

Thanks for reporting this bug!

The new tile release 5.9.1 is now live and contains a fix for this issue.

**Comment by sritimmaraju** [comment]
@NouemanKHAL - This issue still exists

**Comment by NouemanKHAL** [comment]
Hi @sritimmaraju ,
I'll reopen the issue in that case, Is it the same error message? 
Also could you share your OpsManager version?

**Comment by sritimmaraju** [comment]
> Hi @sritimmaraju , I'll reopen the issue in that case, Is it the same error message? Also could you share your OpsManager version?

Yes, Its the same error message, and we're on OpsManager version 2.10.x

**Comment by NouemanKHAL** [comment]
@sritimmaraju Which tile version are you trying to upgrade from?

**Comment by sritimmaraju** [comment]
@NouemanKHAL We are upgrading from 5.8.0
Tried a direct installation of 5.9.1 in a new system - and it ended up with same error

**Comment by NouemanKHAL** [comment]
Hi again @sritimmaraju,

Could you follow the steps in the [README](https://github.com/DataDog/datadog-cluster-monitoring-pivotal-tile/blob/master/README.md) to build a tile from this PR https://github.com/DataDog/datadog-cluster-monitoring-pivotal-tile/pull/114 ?
