### ISSUE TITLE
Release 5.4.1 is missing in VMWare Tanzu Network

### ISSUE THREAD

**Issue by basiszwo** [DataDog/datadog-cluster-monitoring-pivotal-tile#90]
We're running Tanzu Application Services in our company. 

Some weeks ago there was 5.4.0 released which we were waiting for because the update is required for the [datadog application monitoring buildpack release 1.33.0](https://github.com/DataDog/datadog-application-monitoring-pivotal-tile/releases/tag/1.33.0)

Unfortunately the 5.4.0 release had some misconfiguration and was eventually removed from Tanzu Network. From the github releases page we can see that there is a 5.4.1 release which unfortunately is not available in the Tanzu Network.

From what our debugging of version 5.4.0 gave us:

The installation fails because the datadog agent version in the runtime config (4.11.2) does not match the configured agent version (4.12.0).
We downloaded and unpacked the provided tile in version 5.4.0 and indeed one could see that the datadog agent version in tile.yml was still 4.11.2 where it should be 4.12.0

I now had a look into the [5.4.1 release](https://github.com/DataDog/datadog-cluster-monitoring-pivotal-tile/releases/tag/5.4.1). I downloaded the zip file. 

Imo the file `tile/tile-history.yml` should point to the current version 5.4.1 but is pointing to 5.4.0: `version: 5.4.0`

In the file `tile/tile.yml` the agent version is 4.12.1. Just to note that there is a [4.12.2 release](https://github.com/DataDog/datadog-agent-boshrelease/releases/tag/4.12.2). Also to note it's flagged as beta ... but the 4.12.1 release is also 😃 

It would be great to get a working 5.4.1 release available in the tanzu network. Thank you very much!

I hope my issue was not too extensive but I wanted to share everything we have.

**Comment by NouemanKHAL** [comment]
Hi @basiszwo,

Sorry for the inconvience, 5.4.1 was also removed due to some technical issues.

We're currently planning to release 5.5.0 by next week, it will contain the Datadog Agent 7.41.1.

I will update the Github Releases to reflect that information.

Hope that answers your issue.

**Comment by basiszwo** [comment]
@NouemanKHAL sorry bothering you ... any updates? can we help with anything?

**Comment by NouemanKHAL** [comment]
Hi @basiszwo ,
I'm really sorry for the delay, it was out of our control. 
We're doing our best to have a release available as soon as possible.

**Comment by NouemanKHAL** [comment]
Hi again @basiszwo,

The Datadog Cluster Monitoring Tile 5.5.0 is now available on Pivotal Network!

Thanks for your patience :)
